# Generated by Django 4.1 on 2022-08-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "msg",
                    models.CharField(blank=True, default="", max_length=300, null=True),
                ),
            ],
            options={"db_table": "Message",},
        ),
        migrations.CreateModel(
            name="User_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=10)),
            ],
            options={"verbose_name_plural": "UserLogin", "db_table": "User_login",},
        ),
        migrations.CreateModel(
            name="User_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "First_name",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                (
                    "Last_name",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                (
                    "House_No",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "Mobile_No",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "Alternate_No",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "Email_Address",
                    models.CharField(blank=True, default="", max_length=40, null=True),
                ),
                (
                    "Occupation",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                (
                    "total_Members",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "total_Vehicles",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "User_login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="society_app.user_login",
                    ),
                ),
            ],
            options={"verbose_name_plural": "User_Data", "db_table": "UserData",},
        ),
    ]
