# Generated by Django 4.1 on 2022-09-01 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0003_rename_message_message_msg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="Msg", new_name="Message",
        ),
    ]
