# Generated by Django 4.1 on 2022-09-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0004_rename_msg_message_message"),
    ]

    operations = [
        migrations.RenameModel(old_name="Message", new_name="Notification",),
        migrations.AlterModelTable(name="notification", table="Notification",),
    ]
