# Generated by Django 4.1 on 2022-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0005_rename_message_notification_alter_notification_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                (
                    "Email_Address",
                    models.CharField(blank=True, default="", max_length=40, null=True),
                ),
                (
                    "Number",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "Occupation",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
            ],
            options={"db_table": "occupation",},
        ),
    ]
