# Generated by Django 4.1 on 2022-09-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0006_occupation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occupation", old_name="Occupation", new_name="Work",
        ),
    ]
