# Generated by Django 4.1 on 2022-09-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0007_rename_occupation_occupation_work"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occupation", old_name="Email_Address", new_name="email_Address",
        ),
        migrations.RenameField(
            model_name="occupation", old_name="Name", new_name="name",
        ),
        migrations.RenameField(
            model_name="occupation", old_name="Number", new_name="number",
        ),
        migrations.RenameField(
            model_name="occupation", old_name="Work", new_name="work",
        ),
    ]
