# Generated by Django 4.1 on 2022-09-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0008_rename_email_address_occupation_email_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occupation", old_name="email_Address", new_name="email",
        ),
    ]
