# Generated by Django 4.1 on 2022-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0009_rename_email_address_occupation_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
