# Generated by Django 4.1 on 2022-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0010_notification_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="img/")),
            ],
            options={"db_table": "image",},
        ),
    ]
