# Generated by Django 4.1 on 2022-09-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0011_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="image", new_name="image_add",),
    ]
