# Generated by Django 4.1 on 2022-09-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0012_rename_image_image_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image_add",
            name="image",
            field=models.ImageField(upload_to="image"),
        ),
    ]
