# Generated by Django 4.1 on 2022-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society_app", "0015_alter_image_add_image_alter_image_add_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
